/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;

import Controller.DB_Controller;
import Controller.LobbyClient;

/**
 *
 * @author K
 */
public class MsgBoxGUI extends javax.swing.JFrame {

    /**
     * Creates new form MsgBoxGUI
     */
	private LobbyClient lobby;
	private DB_Controller db_cont;
	private String nickname;
	private LobbyGUI gui;
	private BandGUI band;
	private boolean hasLobby;
	private final String colNames[] = { "Sender", "Date", "Time", "Contents"}; // 테이블_컬럼값들
	
    public MsgBoxGUI(LobbyClient lobby, DB_Controller db_cont, LobbyGUI gui, BandGUI band, String nickname, boolean hasLobby) {
    	initComponents();
    	this.lobby = lobby;
    	this.db_cont = db_cont;
    	this.gui = gui;
    	this.band = band;
    	this.nickname = nickname;
    	this.hasLobby = hasLobby;
    	user_id.setText(nickname);
    	getMessage();
    }
    
    public void getMessage() {
    	DefaultTableModel model = new DefaultTableModel(colNames, 0) {
            // Jtable 내용 편집 안되게
            public boolean isCellEditable(int i, int c) {
                return false;
            }
        };
    	ResultSet rs = db_cont.getMessage(nickname);
    	try {
			while (rs.next()) {
				model.addRow(new Object[] { rs.getString("sender"), rs.getString("date"), rs.getString("time"), rs.getString("contents")});
			}
			msgBox.setModel(model);
		} catch (SQLException e) {
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        user_id = new javax.swing.JLabel();
        refresh_btn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        msgBox = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(1000, 200));
        setResizable(false);

        user_id.setText("user 1");

        refresh_btn.setText("refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        msgBox.setBackground(new java.awt.Color(231, 230, 230));
        msgBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Sender", "Date", "Time", "Contents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        msgBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        msgBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msgBoxMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(msgBox);
        msgBox.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (msgBox.getColumnModel().getColumnCount() > 0) {
            msgBox.getColumnModel().getColumn(0).setResizable(false);
            msgBox.getColumnModel().getColumn(1).setResizable(false);
            msgBox.getColumnModel().getColumn(2).setResizable(false);
            msgBox.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(refresh_btn)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(user_id))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(user_id)
                .addGap(10, 10, 10)
                .addComponent(refresh_btn)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	getMessage();
    }                                           

    private void msgBoxMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
    	int row = msgBox.getSelectedRow();
    	String[] data = new String[4];
    	for(int i=0; i<4; i++) {
    		data[i] = (String) msgBox.getValueAt(row, i);
    	}
    	RecvMsgGUI recvMsg = new RecvMsgGUI(db_cont, lobby, data[0], nickname, data[1], data[2], data[3]);
    	recvMsg.open();
    	db_cont.setCheck(nickname, data[0], data[1], data[2]);
    	if(hasLobby)
    		gui.setNotificationBtn();
    	else {
    		gui.setNotificationBtn();
    		band.setNotificationBtn();
    	}
    }                                   

    /**
     * @param args the command line arguments
     */
    public void open() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MsgBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MsgBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MsgBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MsgBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setVisible(true);
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MsgBoxGUI().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable msgBox;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel user_id;
    // End of variables declaration                   
}
