/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import Controller.DB_Controller;
import Controller.LobbyClient;

/**
 *
 * @author K
 */
public class MsgBoxGUI extends javax.swing.JFrame {

    /**
     * Creates new form MsgBoxGUI
     */
	private LobbyClient lobby;
	private DB_Controller db_cont;
	private String nickname;
	private LobbyGUI gui;
	private BandGUI band;
	private boolean hasLobby;
	private final String colNames[] = { "Sender", "Date", "Time", "Contents"}; // 테이블_컬럼값들
	
    public MsgBoxGUI(LobbyClient lobby, DB_Controller db_cont, LobbyGUI gui, BandGUI band, String nickname, boolean hasLobby) {
    	initComponents();
    	this.lobby = lobby;
    	this.db_cont = db_cont;
    	this.gui = gui;
    	this.band = band;
    	this.nickname = nickname;
    	this.hasLobby = hasLobby;
    	user_id.setText(nickname);
    	getMessage();
    }
    
    public void getMessage() {
    	DefaultTableModel model = new DefaultTableModel(colNames, 0) {
            // Jtable 내용 편집 안되게
            public boolean isCellEditable(int i, int c) {
                return false;
            }
        };
    	ResultSet rs = db_cont.getMessage(nickname);
    	try {
			while (rs.next()) {
				model.addRow(new Object[] { rs.getString("sender"), rs.getString("date"), rs.getString("time"), rs.getString("contents")});
			}
			msgBox.setModel(model);
		} catch (SQLException e) {
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        user_id = new javax.swing.JLabel();
        delete_btn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        msgBox = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Message Storage");
        setLocation(new java.awt.Point(1000, 200));
        setResizable(false);

        user_id.setFont(new java.awt.Font("맑은 고딕", 0, 28)); // NOI18N
        user_id.setText("User 1");

        Image i = Toolkit.getDefaultToolkit().getImage("rsc/images/msgBox/delete_btn.png");
        ImageIcon icon = new ImageIcon(i);
        delete_btn.setIcon(icon); // NOI18N
        delete_btn.setContentAreaFilled(false);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        msgBox.setAutoCreateRowSorter(true);
        msgBox.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        msgBox.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        msgBox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"김민범", "2018/11/18", "오전 8시 23분 21초", "테스트 메시지"}
            },
            new String [] {
                "Sender", "Date", "Time", "Contents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        msgBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        msgBox.setShowHorizontalLines(false);
        msgBox.setShowVerticalLines(false);
        msgBox.getTableHeader().setReorderingAllowed(false);
        msgBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msgBoxMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(msgBox);

        i = Toolkit.getDefaultToolkit().getImage("rsc/images/msgBox/msgBox_bg.png");
        icon = new ImageIcon(i);
        bg.setIcon(icon); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(user_id))
            .addGroup(layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(user_id)
                .addGap(39, 39, 39)
                .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg)
        );

        pack();
    }// </editor-fold>                        

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	int row = msgBox.getSelectedRow();
    	String[] data = new String[3];
    	for(int i=0; i<3; i++) {
    		data[i] = (String) msgBox.getValueAt(row, i);
    	}
    	db_cont.deleteMail(nickname, data[0], data[1], data[2]);
    	getMessage();
    }                                           

    private void msgBoxMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
    	int row = msgBox.getSelectedRow();
    	String[] data = new String[4];
    	for(int i=0; i<4; i++) {
    		data[i] = (String) msgBox.getValueAt(row, i);
    	}
    	RecvMsgGUI recvMsg = new RecvMsgGUI(db_cont, lobby, data[0], nickname, data[1], data[2], data[3]);
    	recvMsg.open();
    	db_cont.setCheck(nickname, data[0], data[1], data[2]);
    	if(hasLobby)
    		gui.setNotificationBtn();
    	else {
    		gui.setNotificationBtn();
    		band.setNotificationBtn();
    	}
    }                                  

    /**
     * @param args the command line arguments
     */
    public void open() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MsgBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MsgBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MsgBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MsgBoxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setVisible(true);
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MsgBoxGUI().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bg;
    private javax.swing.JTable msgBox;
    private javax.swing.JButton delete_btn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel user_id;
    // End of variables declaration                   
}
