/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;

import Controller.DB_Controller;
import Controller.Reg_Controller;
import Model.UserData;

/**
 *
 * @author K
 */
public class RegGUI extends javax.swing.JFrame {

    /**
     * Creates new form regGUI
     */
	private DB_Controller db_cont;
	private Reg_Controller reg_cont;
	private UserData user;
	private String ip;
	
    public RegGUI(String ip) {
    	this.ip = ip;
    	initComponents();
        db_cont = new DB_Controller(ip);
        db_cont.Connect();
        reg_cont = new Reg_Controller();
        user = new UserData();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        id_in = new javax.swing.JTextField();
        chk_btn = new javax.swing.JButton();
        error_Msg1 = new javax.swing.JLabel();
        pw_in = new javax.swing.JPasswordField();
        pw_in2 = new javax.swing.JPasswordField();
        error_Msg2 = new javax.swing.JLabel();
        accept_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        nick_in = new javax.swing.JTextField();
        chk_btn2 = new javax.swing.JButton();
        error_Msg3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        
        Image i;
        ImageIcon icon;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setLocation(new java.awt.Point(620, 200));
        setResizable(false);

        id_in.setBackground(new java.awt.Color(231, 230, 230));
        id_in.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        id_in.setForeground(new java.awt.Color(102, 102, 102));
        
        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/check_btn.png");
		icon = new ImageIcon(i);  //이미지 넣기
        chk_btn.setIcon(icon); // NOI18N
        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/check_clicked.png");
		icon = new ImageIcon(i);  //이미지 넣기
        chk_btn.setPressedIcon(icon); // NOI18N
        chk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_btnActionPerformed(evt);
            }
        });

        error_Msg1.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        error_Msg1.setForeground(new java.awt.Color(255, 0, 0));
        error_Msg1.setText(" ");

        pw_in.setBackground(new java.awt.Color(231, 230, 230));
        pw_in.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        pw_in.setForeground(new java.awt.Color(102, 102, 102));

        pw_in2.setBackground(new java.awt.Color(231, 230, 230));
        pw_in2.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        pw_in2.setForeground(new java.awt.Color(102, 102, 102));
        pw_in2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pw_in2KeyReleased(evt);
            }
        });

        error_Msg2.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        error_Msg2.setForeground(new java.awt.Color(255, 0, 0));
        error_Msg2.setText(" ");
        
        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/register_btn.png");
		icon = new ImageIcon(i);  //이미지 넣기
        accept_btn.setIcon(icon); // NOI18N
        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/register_clicekd.png");
		icon = new ImageIcon(i);  //이미지 넣기
        accept_btn.setPressedIcon(icon); // NOI18N
        accept_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_btnActionPerformed(evt);
            }
        });

        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/cancel_btn.png");
		icon = new ImageIcon(i);  //이미지 넣기
        cancel_btn.setIcon(icon); // NOI18N
        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/cancel_clicked.png");
		icon = new ImageIcon(i);  //이미지 넣기
        cancel_btn.setPressedIcon(icon); // NOI18N
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        nick_in.setBackground(new java.awt.Color(231, 230, 230));
        nick_in.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        nick_in.setForeground(new java.awt.Color(102, 102, 102));

        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/check_btn.png");
		icon = new ImageIcon(i);  //이미지 넣기
        chk_btn2.setIcon(icon); // NOI18N
        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/check_clicked.png");
		icon = new ImageIcon(i);  //이미지 넣기
        chk_btn2.setPressedIcon(icon); // NOI18N
        chk_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_btn2ActionPerformed(evt);
            }
        });

        error_Msg3.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        error_Msg3.setForeground(new java.awt.Color(255, 0, 0));
        error_Msg3.setText(" ");

        i = Toolkit.getDefaultToolkit().getImage("rsc/images/Register/register_bg.png");
		icon = new ImageIcon(i);  //이미지 넣기
        bg.setIcon(icon); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(id_in, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(error_Msg1))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(pw_in2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(nick_in, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(accept_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(chk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(error_Msg3))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(error_Msg2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(pw_in, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(chk_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(id_in, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(error_Msg1)
                .addGap(73, 73, 73)
                .addComponent(pw_in2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(nick_in, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(accept_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(chk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(error_Msg3))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(error_Msg2))
            .addGroup(layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(pw_in, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(chk_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg)
        );

        pack();
    }// </editor-fold>                        

    private void chk_btnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	if(db_cont.searchID(id_in.getText())) {
    		error_Msg1.setForeground(new java.awt.Color(255, 0, 0));	
    		error_Msg1.setText("중복되는 ID가 있습니다");
    		reg_cont.id_chk = false;
    	}else {
    		error_Msg1.setForeground(new java.awt.Color(0, 204, 51));
    		error_Msg1.setText("사용가능한 ID입니다");
    		reg_cont.id_chk = true;
    		user.setId(id_in.getText());
    	}
    }                                       

    private void accept_btnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	if(reg_cont.is_OK()) {
    		try {
				db_cont.create(user);				
				dispose();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    }                                          

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	db_cont.Disconnect();
    	dispose();
    }                                          

    private void chk_btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(db_cont.searchNick(nick_in.getText())) {
    		error_Msg3.setForeground(new java.awt.Color(255, 0, 0));	
    		error_Msg3.setText("중복되는 닉네임이 있습니다");
    		reg_cont.nick_chk = false;
    	}else {
    		error_Msg3.setForeground(new java.awt.Color(0, 204, 51));
    		error_Msg3.setText("사용가능한 닉네임입니다");
    		user.setnickName(nick_in.getText());
    		reg_cont.nick_chk = true;
    	}
    }                                        

    private void pw_in2KeyReleased(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
    	if(new String(pw_in.getPassword()).equals(new String(pw_in2.getPassword()))) {    		
    		error_Msg2.setForeground(new java.awt.Color(0, 204, 51));
    		error_Msg2.setText("비밀번호가 일치합니다");
    		reg_cont.pw_chk = true;
    		user.setPassword(new String(pw_in.getPassword()));
    	}else {    		
    		error_Msg2.setForeground(new java.awt.Color(255, 0, 0));	
    		error_Msg2.setText("비밀번호가 일치하지 않습니다");
    		reg_cont.pw_chk = false;    		
    	}
    }                                  

    /**
     * @param args the command line arguments
     */
    public void open() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        setVisible(true);
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegGUI().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton accept_btn;
    private javax.swing.JLabel bg;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton chk_btn;
    private javax.swing.JButton chk_btn2;
    private javax.swing.JLabel error_Msg1;
    private javax.swing.JLabel error_Msg2;
    private javax.swing.JLabel error_Msg3;
    private javax.swing.JTextField id_in;
    private javax.swing.JTextField nick_in;
    private javax.swing.JPasswordField pw_in;
    private javax.swing.JPasswordField pw_in2;
    // End of variables declaration                   
}
