/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DB_Controller;
import Controller.Reg_Controller;
import Model.UserData;

/**
 *
 * @author K
 */
public class RegGUI extends javax.swing.JFrame {

    /**
     * Creates new form regGUI
     */
	DB_Controller db_cont;
	Reg_Controller reg_cont;
	UserData user;
	
    public RegGUI() {
        initComponents();
        db_cont = new DB_Controller();
        db_cont.Connect();
        reg_cont = new Reg_Controller();
        user = new UserData();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        id_in = new javax.swing.JTextField();
        chk_btn = new javax.swing.JButton();
        pw_label = new javax.swing.JLabel();
        pw_label2 = new javax.swing.JLabel();
        error_Msg1 = new javax.swing.JLabel();
        pw_in = new javax.swing.JPasswordField();
        pw_in2 = new javax.swing.JPasswordField();
        error_Msg2 = new javax.swing.JLabel();
        accept_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        nick_label = new javax.swing.JLabel();
        nick_in = new javax.swing.JTextField();
        chk_btn2 = new javax.swing.JButton();
        error_Msg3 = new javax.swing.JLabel();
        
        setTitle("회원가입");
        setLocation(new java.awt.Point(800, 400));
        setResizable(false);

        title.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        title.setText("회원가입");

        id_label.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        id_label.setText("ID");

        id_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_inActionPerformed(evt);
            }
        });

        chk_btn.setText("중복확인");
        chk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_btnActionPerformed(evt);
            }
        });

        pw_label.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        pw_label.setText("비밀번호");

        pw_label2.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        pw_label2.setText("비밀번호 확인");
        
        error_Msg1.setText(" ");

        error_Msg2.setForeground(new java.awt.Color(255, 0, 0));
        //error_Msg2.setText("비밀번호가 일치하지 않습니다.");
        error_Msg2.setText(" ");
        
        pw_in2.addKeyListener(new java.awt.event.KeyAdapter() {
        	public void keyReleased(java.awt.event.KeyEvent evt) {
                pw_in2KeyReleased(evt);
            }
        });       

        accept_btn.setText("가입");
        accept_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_btnActionPerformed(evt);
            }
        });

        cancel_btn.setText("취소");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        nick_label.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        nick_label.setText("닉네임");

        chk_btn2.setText("중복확인");
        chk_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_btn2ActionPerformed(evt);
            }
        });        

        error_Msg3.setForeground(new java.awt.Color(255, 0, 0));
        error_Msg3.setText(" ");
        //error_Msg3.setText("중복된 닉네임이 있습니다.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pw_label))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error_Msg1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id_in, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_btn))
                            .addComponent(pw_in, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pw_label2)
                            .addComponent(nick_label))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(pw_in2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(error_Msg2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(accept_btn)
                                        .addGap(30, 30, 30)
                                        .addComponent(cancel_btn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(error_Msg3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(nick_in, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_btn2)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_btn)
                    .addComponent(id_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_Msg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pw_label)
                    .addComponent(pw_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pw_in2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pw_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(error_Msg2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nick_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nick_label)
                    .addComponent(chk_btn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_Msg3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accept_btn)
                    .addComponent(cancel_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void id_inActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void chk_btnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:    	
    	if(db_cont.searchID(id_in.getText())) {
    		error_Msg1.setForeground(new java.awt.Color(255, 0, 0));	
    		error_Msg1.setText("중복되는 ID가 있습니다");
    		reg_cont.id_chk = false;
    	}else {
    		error_Msg1.setForeground(new java.awt.Color(0, 204, 51));
    		error_Msg1.setText("사용가능한 ID입니다");
    		reg_cont.id_chk = true;
    		user.setId(id_in.getText());
    	}
    }                                       

    private void accept_btnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	if(reg_cont.is_OK()) {
    		try {
				db_cont.create(user);				
				dispose();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    }                                          

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	db_cont.Disconnect();
    	dispose();
    }                                          

    private void chk_btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	if(db_cont.searchNick(nick_in.getText())) {
    		error_Msg3.setForeground(new java.awt.Color(255, 0, 0));	
    		error_Msg3.setText("중복되는 닉네임이 있습니다");
    		reg_cont.nick_chk = false;
    	}else {
    		error_Msg3.setForeground(new java.awt.Color(0, 204, 51));
    		error_Msg3.setText("사용가능한 닉네임입니다");
    		user.setnickName(nick_in.getText());
    		reg_cont.nick_chk = true;
    	}
    }
    
    private void pw_in2KeyReleased(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
    	if(new String(pw_in.getPassword()).equals(new String(pw_in2.getPassword()))) {    		
    		error_Msg2.setForeground(new java.awt.Color(0, 204, 51));
    		error_Msg2.setText("비밀번호가 일치합니다");
    		reg_cont.pw_chk = true;
    		user.setPassword(new String(pw_in.getPassword()));
    	}else {    		
    		error_Msg2.setForeground(new java.awt.Color(255, 0, 0));	
    		error_Msg2.setText("비밀번호가 일치하지 않습니다");
    		reg_cont.pw_chk = false;    		
    	}
    } 
    
    /**
     * @param args the command line arguments
     */
    public void open() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */    	
    	
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setVisible(true);
        /* Create and display the form 	
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegGUI().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton accept_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton chk_btn;
    private javax.swing.JButton chk_btn2;
    private javax.swing.JLabel error_Msg1;
    private javax.swing.JLabel error_Msg2;
    private javax.swing.JLabel error_Msg3;
    private javax.swing.JTextField id_in;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField nick_in;
    private javax.swing.JLabel nick_label;
    private javax.swing.JPasswordField pw_in;
    private javax.swing.JPasswordField pw_in2;
    private javax.swing.JLabel pw_label;
    private javax.swing.JLabel pw_label2;
    private javax.swing.JLabel title;
    // End of variables declaration                   
}
