///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package View;
//
//import Controller.DB_Controller;
//
///**
// *
// * @author K
// */
//public class UserGUI extends javax.swing.JFrame {
//
//    /**
//     * Creates new form userGUI
//     */
//	private DB_Controller db_cont;
//	private LobbyGUI lobby;
//	private String nickname;
//	private boolean setNick = false;
//	private boolean chk_pass = false;
//	private boolean chk_pass2 = false;
//	
//    public UserGUI(DB_Controller db_cont, LobbyGUI lobby, String nickname) {
//    	this.db_cont = db_cont;
//    	this.lobby = lobby;
//    	this.nickname = nickname;
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        id_label = new javax.swing.JLabel();
//        user_id = new javax.swing.JLabel();
//        pw_in1 = new javax.swing.JPasswordField();
//        pw_label = new javax.swing.JLabel();
//        pw_in2 = new javax.swing.JPasswordField();
//        pw_chk_label = new javax.swing.JLabel();
//        pw_label2 = new javax.swing.JLabel();
//        pw_chk_label2 = new javax.swing.JLabel();
//        pw_in3 = new javax.swing.JPasswordField();
//        pw_in4 = new javax.swing.JPasswordField();
//        nick_label = new javax.swing.JLabel();
//        nick_in = new javax.swing.JTextField();
//        chk_btn = new javax.swing.JButton();
//        save_btn = new javax.swing.JButton();
//        close_btn = new javax.swing.JButton();
//        errorMsg = new javax.swing.JLabel();
//        errorMsg2 = new javax.swing.JLabel();
//        errorMsg3 = new javax.swing.JLabel();
//        errorMsg4 = new javax.swing.JLabel();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setLocation(new java.awt.Point(700, 300));
//        setResizable(false);
//
//        id_label.setText("user ID");
//
//        user_id.setText("user id");
//
//        pw_in1.setText("password");
//
//        pw_label.setText("password");
//
//        pw_in2.setText("password");
//        pw_in2.setToolTipText("");
//        pw_in2.addKeyListener(new java.awt.event.KeyAdapter() {
//            public void keyReleased(java.awt.event.KeyEvent evt) {
//                pw_in2KeyReleased(evt);
//            }
//        });
//
//        pw_chk_label.setText("passwd_chk");
//
//        pw_label2.setText("change passwd");
//
//        pw_chk_label2.setText("passwd _chk");
//
//        pw_in3.setText("password");
//
//        pw_in4.setText("password");
//        pw_in4.addKeyListener(new java.awt.event.KeyAdapter() {
//            public void keyReleased(java.awt.event.KeyEvent evt) {
//                pw_in4KeyReleased(evt);
//            }
//        });
//
//        nick_label.setText("nickname");
//
//        nick_in.setText("nickname");
//
//        chk_btn.setText("chk");
//        chk_btn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                chk_btnActionPerformed(evt);
//            }
//        });
//
//        save_btn.setText("save");
//        save_btn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                save_btnActionPerformed(evt);
//            }
//        });
//
//        close_btn.setText("close");
//        close_btn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                close_btnActionPerformed(evt);
//            }
//        });
//
//        errorMsg.setForeground(new java.awt.Color(255, 0, 0));
//        errorMsg.setText(" ");
//
//        errorMsg2.setForeground(new java.awt.Color(255, 0, 0));
//        errorMsg2.setText(" ");
//
//        errorMsg3.setForeground(new java.awt.Color(255, 0, 0));
//        errorMsg3.setText(" ");
//
//        errorMsg4.setForeground(new java.awt.Color(255, 0, 0));
//        errorMsg4.setText(" ");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(65, 65, 65)
//                .addComponent(id_label)
//                .addGap(59, 59, 59)
//                .addComponent(user_id))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(40, 40, 40)
//                .addComponent(pw_label)
//                .addGap(47, 47, 47)
//                .addComponent(pw_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(20, 20, 20)
//                .addComponent(pw_chk_label)
//                .addGap(49, 49, 49)
//                .addComponent(pw_in2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(120, 120, 120)
//                .addComponent(errorMsg))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(10, 10, 10)
//                .addComponent(pw_label2)
//                .addGap(37, 37, 37)
//                .addComponent(pw_in3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(30, 30, 30)
//                .addComponent(pw_chk_label2)
//                .addGap(34, 34, 34)
//                .addComponent(pw_in4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(120, 120, 120)
//                .addComponent(errorMsg2))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(50, 50, 50)
//                .addComponent(nick_label)
//                .addGap(49, 49, 49)
//                .addComponent(nick_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(63, 63, 63)
//                .addComponent(chk_btn))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(50, 50, 50)
//                .addComponent(save_btn)
//                .addGap(119, 119, 119)
//                .addComponent(close_btn))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(80, 80, 80)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(errorMsg3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(errorMsg4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(48, 48, 48)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(id_label)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addComponent(user_id)))
//                .addGap(32, 32, 32)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(pw_label)
//                    .addComponent(pw_in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(16, 16, 16)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(pw_chk_label)
//                    .addComponent(pw_in2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(6, 6, 6)
//                .addComponent(errorMsg)
//                .addGap(2, 2, 2)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(pw_label2)
//                    .addComponent(pw_in3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(16, 16, 16)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(pw_chk_label2)
//                    .addComponent(pw_in4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(6, 6, 6)
//                .addComponent(errorMsg2)
//                .addGap(12, 12, 12)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(10, 10, 10)
//                        .addComponent(nick_label))
//                    .addComponent(nick_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(chk_btn))
//                .addGap(6, 6, 6)
//                .addComponent(errorMsg3)
//                .addGap(18, 18, 18)
//                .addComponent(errorMsg4)
//                .addGap(20, 20, 20)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(save_btn)
//                    .addComponent(close_btn)))
//        );
//
//        pack();
//    }// </editor-fold>                        
//
//    private void chk_btnActionPerformed(java.awt.event.ActionEvent evt) {                                        
//        // TODO add your handling code here:
//    	if(db_cont.searchNick(nick_in.getText())) {
//    		errorMsg3.setForeground(new java.awt.Color(255, 0, 0));	
//    		errorMsg3.setText("중복되는 닉네임이 있습니다");
//    		setNick = true;
//    	}else {
//    		errorMsg3.setForeground(new java.awt.Color(0, 204, 51));
//    		errorMsg3.setText("사용가능한 닉네임입니다");    		
//    		setNick = true;
//    	}
//    }                                       
//
//    private void pw_in2KeyReleased(java.awt.event.KeyEvent evt) {                                   
//        // TODO add your handling code here:
//    	if(new String(pw_in1.getPassword()).equals(new String(pw_in2.getPassword()))) {    		
//    		errorMsg.setForeground(new java.awt.Color(0, 204, 51));
//    		errorMsg.setText("비밀번호가 일치합니다");
//    		chk_pass = true;
//    	}else {    		
//    		errorMsg.setForeground(new java.awt.Color(255, 0, 0));	
//    		errorMsg.setText("비밀번호가 일치하지 않습니다");
//    		chk_pass = false;
//    	}
//    }                                  
//
//    private void pw_in4KeyReleased(java.awt.event.KeyEvent evt) {                                   
//        // TODO add your handling code here:
//    	if(new String(pw_in3.getPassword()).equals(new String(pw_in4.getPassword()))) {    		
//    		errorMsg2.setForeground(new java.awt.Color(0, 204, 51));
//    		errorMsg2.setText("비밀번호가 일치합니다");
//    		chk_pass2 = true;
//    	}else {    		
//    		errorMsg2.setForeground(new java.awt.Color(255, 0, 0));	
//    		errorMsg2.setText("비밀번호가 일치하지 않습니다");
//    		chk_pass2 = false;
//    	}
//    }                                  
//
//    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//    	if(chk_pass && chk_pass2 && setNick) {
//    		String id = db_cont.getID(nickname);
//    		if(db_cont.Password_Chk(id, new String(pw_in1.getPassword()))){
//    			if(db_cont.change(nickname, new String(pw_in3.getPassword()), nick_in.getText())) {
//    				lobby.setNickname(nickname);
//    				dispose();
//    			}
//    		}else {
//    			errorMsg4.setText("기존 비밀번호를  확인해주세요");
//    		}
//    	}else {
//    		errorMsg4.setText("다시한번 확인해주세요");
//    	}
//    }                                        
//
//    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//    	dispose();
//    }                                         
//
//    /**
//     * @param args the command line arguments
//     */
//    public void open() {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        setVisible(true);
//        /* Create and display the form */
//        /*java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserGUI().setVisible(true);
//            }
//        });*/
//    }
//
//    // Variables declaration - do not modify                     
//    private javax.swing.JButton chk_btn;
//    private javax.swing.JButton close_btn;
//    private javax.swing.JLabel errorMsg;
//    private javax.swing.JLabel errorMsg2;
//    private javax.swing.JLabel errorMsg3;
//    private javax.swing.JLabel errorMsg4;
//    private javax.swing.JLabel id_label;
//    private javax.swing.JTextField nick_in;
//    private javax.swing.JLabel nick_label;
//    private javax.swing.JLabel pw_chk_label;
//    private javax.swing.JLabel pw_chk_label2;
//    private javax.swing.JPasswordField pw_in1;
//    private javax.swing.JPasswordField pw_in2;
//    private javax.swing.JPasswordField pw_in3;
//    private javax.swing.JPasswordField pw_in4;
//    private javax.swing.JLabel pw_label;
//    private javax.swing.JLabel pw_label2;
//    private javax.swing.JButton save_btn;
//    private javax.swing.JLabel user_id;
//    // End of variables declaration                   
//}
